<%!
from alembic.script import ScriptDirectory
from alembic.runtime.environment import EnvironmentContext
%>
<%!
# This is a thin extension of the standard Alembic script template.
%>
<%autoescape false %>
'''Generated by Alembic.'''
<%endautoescape%>
